name: Spotless Check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Spotless Check
    runs-on: ubuntu-latest
    # TODO make sure this is correct container
    container: wpilib/roborio-cross-ubuntu:2025-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
      - name: Run SpotlessCheck
        run: ./gradlew SpotlessCheck
